[package]
name = "minimap-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[[bin]]
name = "minimap"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
minimap-android = { version = "0.2.0", path = "../minimap-android" }
minimap-core = { version = "0.2.0", path = "../minimap-core" }
minimap-graph = { version = "0.2.0", path = "../minimap-graph" }
minimap-repo = { version = "0.2.0", path = "../minimap-repo" }
minimap-schemas = { version = "0.2.0", path = "../minimap-schemas" }
clap = { workspace = true, features = ["env"] }
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
tempfile.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
